#name: Build and Test
#
#on:
#  push:
#    branches:
#    - '**'
#    tags-ignore:
#    - '**'
#
#env:
#  SECRETS: ${{ toJSON(secrets) }}
#
#jobs:
#  build-dockerfile:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - uses: actions/checkout@v4
#      with:
#        repository: journeyapps-platform/ci-actions
#        token: ${{ secrets.SHARED_GH_TOKEN }}
#        path: .github/ci
#        ref: v1
#    - uses: ./.github/ci/actions/docker-build
#      name: Docker Build
#
#  run-tests:
#    name: Test
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - uses: actions/checkout@v4
#      with:
#        repository: journeyapps-platform/ci-actions
#        token: ${{ secrets.SHARED_GH_TOKEN }}
#        path: .github/ci
#        ref: v1
#
#    - name: Setup NodeJS
#      uses: actions/setup-node@v2
#      with:
#        node-version: 20
#    - name: Install PNPM
#      run: npm i -g pnpm@9
#
#    - name: Install Dependencies
#      uses: ./.github/ci/actions/npm-install
#      with:
#        client: pnpm
#
#    - name: Build
#      shell: bash
#      run: pnpm build
##    - name: Test
##      shell: bash
##      run: pnpm test
#
#  preview-deploy:
#    name: Deploy (Preview)
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - uses: actions/checkout@v4
#      with:
#        repository: journeyapps-platform/ci-actions
#        token: ${{ secrets.SHARED_GH_TOKEN }}
#        path: ./.github/ci
#        ref: v1
#
#    - uses: ./.github/ci/actions/setup-tools
#      name: Setup Tools
#      with:
#        pulumi-version: 3.51.0
#
#    - uses: ./.github/ci/actions/micro-deploy
#      name: Deploy (preview)
#      with:
#        preview: true
#        environment: production
